- name: Configue the backend server
  hosts: backend
  become: yes
  tasks:
  - name: Disable the package
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install node js package
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Creating a user
    ansible.builtin.user:
      name: expense

  - name: Creating a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Unzip the backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: Install the npm packages
    community.general.npm:
      path: /app