- name: Configue the backend server
  hosts: backend
  become: yes
  tasks:
  - name: Disable the package
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install node js package
    ansible.builtin.package:
      name: nodejs
      state: present
