- name: Configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install the nginx server
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: remove the default content of the nginx server
    ansible.builtin.file:
      path: rm -rf /usr/share/nginx/html/*
      state: directory

  - name: Download the file
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  - name: Change the directory
    ansible.builtin.command: cd /usr/share/nginx/html
  
  - name: Unzip the file
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes